### ISSUE TITLE
npm ERR! invalid: typescript@2.4.2

### ISSUE THREAD

**Issue by Ofer-Gal** [sabitertan/spfx-react-pnp-example#1]
Followed the instructions but  
"npm list typescript" Showed on the line before last: "npm ERR! invalid: typescript@2.4.2"
So Installed "Npm i typescript@2.4.2 -g"  did not help
then "Npm i typescript@2.4.2 --save" 
Now that line shows "typescript@2.2.2" and gulp test fails.
Any suggestions?

**Comment by sabitertan** [comment]
@Ofer-Gal , Can you share your npm environment, I have recently tested on:
Windows 10
Node 8.12.0
npm 6.7.0
Sharepoint 2016 FP2
everything works fine. 
FYI this version never tested on node 6 or node 10. But I will give a try to node 10.
Thanks.

**Comment by Ofer-Gal** [comment]
Turns out when it shows: "-- typescript@2.4.2  invalid" it still gulps the tasks fine. So I don't care for it
My NPM is 6.4.1 (Should I upgrade to 6.7.0 ?)
Node is "v8.14.0" 
Windows 10

**Comment by sabitertan** [comment]
tested with Node 8.15.1 and npm 6.9.0 only difference I got in package-lock.json file is a dependency for @microsoft/gulp-core-build-typescript
that module depends on "typescript": "~2.2.2" so I changed to "typescript": "~2.4.2"
also there is a dependency block like below:
`        "typescript": {
          "version": "2.2.2",
          "resolved": "https://registry.npmjs.org/typescript/-/typescript-2.2.2.tgz",
          "integrity": "sha1-YGAiUIR5tV/6NotY/uljoD39eww=",
          "dev": true
        }`
I replace it with settings below
`	    "typescript": {
          "version": "2.4.2",
          "resolved": "https://registry.npmjs.org/typescript/-/typescript-2.4.2.tgz",
          "integrity": "sha1-+DlfhdRZJ2BnyYiqQYN6j4KHCEQ=",
          "dev": true
        }`
and it start working again.

Also tested with node 10.15.3 + npm 6.9.0 but that famous ERR_SSL_PROTOCOL_ERROR problem is happening. Didnt spend to much time for node 10 as it is not supported by SPFx team at all.

**Comment by sabitertan** [comment]
@Ofer-Gal , Yes please try with npm >= 6.7.0

**Comment by Ofer-Gal** [comment]
If you tell me how to change npm version without changing node version :-)

**Comment by sabitertan** [comment]
npm i -g npm@6.7.0
depends on how you install node you may need to start cmd/powershell as admin.

**Comment by Ofer-Gal** [comment]
I tried this and got:
`λ npm i -g npm@6.7.0
npm ERR! path C:\Program Files\nodejs\npm.cmd
npm ERR! code EEXIST
npm ERR! Refusing to delete C:\Program Files\nodejs\npm.cmd: is outside C:\Program Files\nodejs\node_modules\npm and not a link
npm ERR! File exists: C:\Program Files\nodejs\npm.cmd
npm ERR! Move it away, and try again.`
If I remove C:\Program Files\nodejs\npm.cmd , it will not work anymore

**Comment by sabitertan** [comment]
@Ofer-Gal  Can you try running cmder as Administrator before you run "npm i -g npm@6.7.0"?

**Comment by Ofer-Gal** [comment]
Nice. that worked.
Thx
